// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/chaiyapluek/go-htmx/templates"

func GeneralQuarters() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"row\"><div class=\"col\"><img src=\"/static/images/general-quarter.jpg\" alt=\"general quarter room\" class=\"img-fluid img-thumbnail mx-auto d-block room-image\"></div></div><div class=\"row\"><div class=\"col\"><h1>General's Quarters</h1><p>Aliquet porttitor lacus luctus accumsan. Ut lectus arcu bibendum at varius vel pharetra vel. Sed velit dignissim sodales ut eu sem integer vitae. Adipiscing enim eu turpis egestas pretium aenean pharetra. Lobortis elementum nibh tellus molestie nunc. Arcu ac tortor dignissim convallis aenean et tortor at risus. Ac tortor dignissim convallis aenean et tortor at risus viverra. Morbi non arcu risus quis varius. Ac turpis egestas integer eget aliquet. Amet risus nullam eget felis eget nunc. Ultrices dui sapien eget mi. Amet cursus sit amet dictum sit. Tristique senectus et netus et malesuada fames. Nibh venenatis cras sed felis eget velit aliquet. Et leo duis ut diam quam. In tellus integer feugiat scelerisque varius morbi enim nunc. Bibendum enim facilisis gravida neque. Arcu dui vivamus arcu felis bibendum ut tristique et.</p></div></div><div class=\"row\"><div class=\"col text-center\"><a href=\"/make-reservation-gq\" class=\"btn btn-success\">Check Availability</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = templates.Layout(nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
