// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/chaiyapluek/go-htmx/templates"

func MajorSuite() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"row\"><div class=\"col\"><img src=\"/static/images/major-suite.jpg\" alt=\"major suite room\" class=\"img-fluid img-thumbnail mx-auto d-block room-image\"></div></div><div class=\"row\"><div class=\"col\"><h1>Major's Suite</h1><p>Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Sem et tortor consequat id porta nibh venenatis cras sed. Non odio euismod lacinia at quis risus sed. Suspendisse interdum consectetur libero id faucibus. Adipiscing at in tellus integer feugiat scelerisque varius morbi. In hac habitasse platea dictumst. Mi quis hendrerit dolor magna eget est. Ut consequat semper viverra nam libero. Platea dictumst quisque sagittis purus sit amet. Feugiat in fermentum posuere urna nec tincidunt praesent. Purus sit amet volutpat consequat mauris nunc congue. Consequat interdum varius sit amet mattis vulputate enim. Sed vulputate odio ut enim blandit. Purus semper eget duis at tellus at urna condimentum. Donec adipiscing tristique risus nec. Sit amet nisl purus in mollis nunc. Euismod elementum nisi quis eleifend quam adipiscing vitae. Egestas purus viverra accumsan in.</p></div></div><div class=\"row\"><div class=\"col text-center\"><a href=\"/make-reservation-ms\" class=\"btn btn-success\">Check Availability</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = templates.Layout(nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
